project:
  title: "os-2023"
  render:
    - "projet.qmd"  
    - "syllabus.qmd"
    - "tps/*.qmd"
    - "examens/*.qmd"
  output-dir: out

format:
  pdf:
    geometry:
    - top=20mm
    - left=25mm
    - right=25mm

number-sections: true
lang: fr

include-in-header: 
  text: |
    \usepackage{fvextra}
    \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
